version: '3.8'
services:
  api:
    depends_on:
      - db
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:${SERVER_PORT}
    environment:
      - MYSQL_DATABASE=demo
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

    networks:
      - spring-mysql
  db:
    container_name: mysql-dev
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
    ports:
      - 3307:3307
volumes:
  db-data:
networks:
  spring-mysql:
  
